avatar: https://images.wanlu.fun/picgo/202312091554708.jpg
background: # 既是博客的背景，又是文章默认头图
    path: https://images.wanlu.fun/picgo/202312101223699.jpg
    width: 1280
    height: 726

favicon:
  href: /favicon.ico # 网站图标
  type: image/x-icon # 图标类型，可能的值有(image/png, image/vnd.microsoft.icon, image/x-icon, image/gif)

function: # 功能开关，可选值（true,false）
  globalToc: true # 开启该功能会自动开启文章 TOC（文章目录） 功能
  wordCount: true # 是否开启文章字数统计 (true, false)
  copyCode: true # 是否允许复制代码块

imageCDN: # 图片 CDN 功能
  enable: false # 开启该功能
  origin: /../../images/ # 图片原始目录
  to: https://cdn.jsdelivr.net/gh/nexmoe/nexmoe.github.io@latest/images/ # 图片 CDN 域名

# 自定义样式，启用后可在站点的source文件夹下新建custom.css自定义站点样式
customStyles:
  - custom.css
  
# 附加图标库 使用说明：https://docs.nexmoe.com/config/icon
iconlib: # //at.alicdn.com/t/font_1038733_0xvrvpg9c0r.css

menu:
    HomePage:
      - /
      - icon-home
    Archives:
      - /archive.html
      - icon-container
    Friend:
      - /PY.html
    Website Status:
      - https://status.wanlu.fun/
      - icon-areachart
    Profile Page:
      - https://home.wanlu.fun/
      - icon-info-circle

widgets:
    - name: search
      enable: true
      options: 
        search: 
            type: local
            url: https://cn.bing.com/search?q=site:nexmoe.com # 搜索引擎地址，在type为swiftype时无效 e.g:https://www.google.com/search?q={你的博客链接}
            id: <swiftype-id> # swiftype的id，见启用教程。在type为engine时无效
    - name: social
      enable: true
      options: 
        social:
          GitHub:
            - https://github.com/wanlufun/
            - icon-github
            - rgb(249, 174, 8)
            - rgba(249, 174, 8, .1)
          Mail:
            - mailto:wanlu@wanlu.fun
            - icon-mail-fill
            - rgb(231, 106, 141)
            - rgba(231, 106, 141, .1)
          RSS:
            - https://www.wanlu.fun/atom.xml
            - icon-rss
            - rgb(247, 132, 34)
            - rgba(247, 132, 34, .1)
    - name: category
      enable: true

    - name: tagcloud
      enable: true
      options: 
        maxTagcloud: 17  # 标签云组件显示的标签数量，0 表示不限制

    - name: hitokoto # 一言 widget
      enable: true
      options: 
        widgetHitokoto: # 一言组件
            loading_placeholder: '🚀 获取中...' # 正在一言时的占位符
            loading_error_placeholder: '🐞 获取失败...' # 加载一言失败时的占位符
            category: i

    - name: archive #settings: widgetAchive
      enable: true
      options:
        widgetAchive: #文章归档组件
            archive_type: 'year' #按月展示还是按年展示
            show_count: true  #是否展示数量

    - name: recent_posts
      enable: true

copyTip: false

slotHead: | 
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-4D4ZJ9G024"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag("js", new Date());

    gtag("config", "G-4D4ZJ9G024");
  </script>
  <link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/katex/dist/katex.min.css"
  />

slotFooter: | 
  <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2058306854838448" crossorigin="anonymous"></script>

# 自定义侧边栏尾部内容
slotSidebar: |
  <br><a target="_blank" href="https://beian.miit.gov.cn/">	鄂ICP备2023019257号-1</a>

# 评论框插槽
slotComment: |
  <script src="https://giscus.app/client.js"
        data-repo="StudentWanLu/StudentWanLu.github.io"
        data-repo-id="R_kgDOK37mFg"
        data-category="Announcements"
        data-category-id="DIC_kwDOK37mFs4CboO_"
        data-mapping="title"
        data-strict="0"
        data-reactions-enabled="1"
        data-emit-metadata="0"
        data-input-position="top"
        data-theme="preferred_color_scheme"
        data-lang="zh-CN"
        data-loading="lazy"
        crossorigin="anonymous"
        async>
  </script>

slotCopyright: | 
  <strong>版权声明：</strong>本文采用 <a href="https://creativecommons.org/licenses/by-nc-sa/3.0/cn/deed.zh" target="_blank">CC BY-NC-SA 3.0 CN</a> 协议进行许可

slotArticleEnd: ~
