# Site
title: 挽风技术
subtitle: '挽风'
description: '一个热爱生活并且乐观的程序员小子'
keywords: 初原挽风,挽风,Java,TS,JS,Vue,React,C/C++,Algorithm,生活
author: 初原挽风
language: zh-CN
timezone: Asia/Shanghai

# URL
url: https://www.wanlu.fun
root: /
permalink: :abbrlink.html
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# abbrlink
abbrlink:
  alg: crc32
  rep: hex

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true

syntax_highlighter: highlight.js
highlight:
  enable: true
  auto_detect: true
  line_number: true
  wrap: true
  hljs: true

prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
meta_generator: true

# Date / Time format
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
include:
exclude:
ignore:

# Extensions
theme: nexmoe

# json content
jsonContent:
  meta: false
  pages: false
  posts:
    title: true
    date: false
    path: true
    text: true
    raw: false
    content: false
    slug: false
    updated: false
    comments: false
    link: false
    permalink: false
    excerpt: false
    categories: false
    tags: false

# Adds nofollow attribute to all external links in your hexo blog posts automatically.
nofollow:
  enable: true
  exclude:
    - wanlu.fun

# Generate SEO-friendly sitemap.
sitemap:
  path: sitemap.xml

# markdown
markdown:
  preset: 'default'
  render:
    html: true
    xhtmlOut: false
    langPrefix: 'language-'
    breaks: true
    linkify: true
    typographer: true
    quotes: '“”‘’'
  enable_rules:
  disable_rules:
  plugins:
    - markdown-it-footnote
    - markdown-it-task-lists
    - name: '@renbaoshuo/markdown-it-katex'
      options:
        skipDelimitersCheck: true

# Deployment
deploy:
  type: sftp
  host: <host>
  user: <user>
  pass: <password>
  remotePath: [ remote path ]
  port: [ port ]
  privateKey: [ path/to/privateKey ]
  passphrase: [ passphrase ]
  agent: [ path/to/agent/socket ]
